services:
  - type: web
    name: wellfound
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: ItisGreatToBeAlive
      - key: MONGODB_URI
        value: mongodb+srv://rachitpanwar:kanekikun@cluster0.dmxti.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
