services:
  - type: web
    name: wellfound-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: COHERE_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
